### ISSUE TITLE
能否不全删除远程文件

### ISSUE THREAD

**Issue by inkss** [75k/hexo-deployer-cos-enhanced#1]
只能删除多余文件吗？能否加一个忽略列表，可以对部分文件忽略删除。

**Comment by inkss** [comment]
此外在使用的过程中发现了一处 BUG ：如果存在着多个部署项目时，程序报错无法识别配置项目。

因为多个部署需要在 type 的前面加上 `-` ，但是 **加上后就报错，去掉就能正常运行** 。

看了一下源码。报错是 `checkConfigs` 函数输出的，或许是 `config.deploy` 无法识别到多个项目吧。

所以打算直接赋值，就在 `let cfgs = config.deploy` 下面加上：

```js
cfgs.bucket = "......";
cfgs.region = ".......";
cfgs.secretId = "......";
cfgs.secretKey = "......";
```
此时程序能够正常输出，起码是能部署到对象存储了。此外还有另外一点，cdn 配置部分不知道如何解决。它直进 `if(!cfgs.cdnConfig)` 判断里返回了。

**Comment by inkss** [comment]
忽略文件这里，有一些思路：主要是解决全部删除和判文件上。删除部分似乎是一个数组，然后能在提交之前先把不想被删除的文件剔除出数组，然后判断部分跳过特定 MD 值的判断？

**Comment by 75k** [comment]
比较简单的办法：可以把要忽略的文件，在本地也存放一份。MD5一样的话，不会再次上传，也不会删除远程文件。暂时没有时间维护这个仓库了，亲自己研究下吧。

**Comment by inkss** [comment]
好吧，那我自己瞅瞅、
